// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CarBaseInfo struct {
	Id        int64   `json:"id"`
	BrandName string  `json:"brandName"`
	Series    string  `json:"series"`
	ModelName string  `json:"modelName"`
	Price     float64 `json:"price"`
	CoverImg  string  `json:"coverImg"`
}

type CarDetailReq struct {
	Id int64 `path:"id"`
}

type CarDetailResp struct {
	BaseInfo CarBaseInfo            `json:"baseInfo"`
	Specs    map[string]interface{} `json:"specs"`
	Images   []string               `json:"images"`
	VideoUrl string                 `json:"videoUrl"`
}

type GetMyReviewsReq struct {
	PageIndex int `form:"pageIndex,optional,default=1"`
	PageSize  int `form:"pageSize,optional,default=10"`
}

type GetMyReviewsResp struct {
	Total int64          `json:"total"`
	List  []MyReviewInfo `json:"list"`
}

type GetReviewListReq struct {
	ModelId   int64 `form:"modelId"`
	PageIndex int   `form:"pageIndex,default=1"`
	PageSize  int   `form:"pageSize,default=10"`
}

type GetReviewListResp struct {
	Total int64        `json:"total"`
	List  []ReviewInfo `json:"list"`
}

type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
	Uid   int64  `json:"uid"`
}

type MyReviewInfo struct {
	Id         int64   `json:"id"`
	ModelId    int64   `json:"modelId"`
	CarName    string  `json:"carName"`
	CarImg     string  `json:"carImg"`
	Score      float64 `json:"score"`
	Content    string  `json:"content"`
	CreateTime string  `json:"createTime"`
}

type PostReviewReq struct {
	ModelId int64   `json:"modelId"`
	Score   float64 `json:"score"`
	Content string  `json:"content"`
}

type ReviewInfo struct {
	Id         int64   `json:"id"`
	Uid        int64   `json:"uid"`
	Nickname   string  `json:"nickname"`
	Avatar     string  `json:"avatar"`
	Score      float64 `json:"score"`
	Content    string  `json:"content"`
	Likes      int64   `json:"likes"`
	CreateTime string  `json:"createTime"`
}

type SearchCarReq struct {
	Keyword   string  `form:"keyword,optional"`
	BrandId   int64   `form:"brandId,optional"`
	MinPrice  float64 `form:"minPrice,optional"`
	MaxPrice  float64 `form:"maxPrice,optional"`
	PageIndex int     `form:"pageIndex,default=1"`
	PageSize  int     `form:"pageSize,default=10"`
}

type SearchCarResp struct {
	Total int64         `json:"total"`
	List  []CarBaseInfo `json:"list"`
}

type UpdateUserReq struct {
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type UpdateUserResp struct {
	Message string `json:"message"`
}

type UserInfoResp struct {
	Uid      int64  `json:"uid"`
	Phone    string `json:"phone"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}
