// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CarBaseInfo struct {
	Id        int64   `json:"id"`
	BrandName string  `json:"brandName"`
	Series    string  `json:"series"`
	ModelName string  `json:"modelName"`
	Price     float64 `json:"price"`
	CoverImg  string  `json:"coverImg"`
}

type CarDetailReq struct {
	Id int64 `path:"id"`
}

type CarDetailResp struct {
	BaseInfo CarBaseInfo            `json:"baseInfo"`
	Specs    map[string]interface{} `json:"specs"`
	Images   []string               `json:"images"`
	VideoUrl string                 `json:"videoUrl"`
}

type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
	Uid   int64  `json:"uid"`
}

type SearchCarReq struct {
	Keyword   string  `form:"keyword,optional"`
	BrandId   int64   `form:"brandId,optional"`
	MinPrice  float64 `form:"minPrice,optional"`
	MaxPrice  float64 `form:"maxPrice,optional"`
	PageIndex int     `form:"pageIndex,default=1"`
	PageSize  int     `form:"pageSize,default=10"`
}

type SearchCarResp struct {
	Total int64         `json:"total"`
	List  []CarBaseInfo `json:"list"`
}
