// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	carBrandsFieldNames          = builder.RawFieldNames(&CarBrands{})
	carBrandsRows                = strings.Join(carBrandsFieldNames, ",")
	carBrandsRowsExpectAutoSet   = strings.Join(stringx.Remove(carBrandsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	carBrandsRowsWithPlaceHolder = strings.Join(stringx.Remove(carBrandsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCarBrandsIdPrefix = "cache:carBrands:id:"
)

type (
	carBrandsModel interface {
		Insert(ctx context.Context, data *CarBrands) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CarBrands, error)
		Update(ctx context.Context, data *CarBrands) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCarBrandsModel struct {
		sqlc.CachedConn
		table string
	}

	CarBrands struct {
		Id      uint64 `db:"id"`
		Name    string `db:"name"`
		Logo    string `db:"logo"`
		Initial string `db:"initial"`
		Sort    int64  `db:"sort"`
	}
)

func newCarBrandsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCarBrandsModel {
	return &defaultCarBrandsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`car_brands`",
	}
}

func (m *defaultCarBrandsModel) Delete(ctx context.Context, id uint64) error {
	carBrandsIdKey := fmt.Sprintf("%s%v", cacheCarBrandsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, carBrandsIdKey)
	return err
}

func (m *defaultCarBrandsModel) FindOne(ctx context.Context, id uint64) (*CarBrands, error) {
	carBrandsIdKey := fmt.Sprintf("%s%v", cacheCarBrandsIdPrefix, id)
	var resp CarBrands
	err := m.QueryRowCtx(ctx, &resp, carBrandsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", carBrandsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCarBrandsModel) Insert(ctx context.Context, data *CarBrands) (sql.Result, error) {
	carBrandsIdKey := fmt.Sprintf("%s%v", cacheCarBrandsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, carBrandsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Logo, data.Initial, data.Sort)
	}, carBrandsIdKey)
	return ret, err
}

func (m *defaultCarBrandsModel) Update(ctx context.Context, data *CarBrands) error {
	carBrandsIdKey := fmt.Sprintf("%s%v", cacheCarBrandsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, carBrandsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Logo, data.Initial, data.Sort, data.Id)
	}, carBrandsIdKey)
	return err
}

func (m *defaultCarBrandsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCarBrandsIdPrefix, primary)
}

func (m *defaultCarBrandsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", carBrandsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCarBrandsModel) tableName() string {
	return m.table
}
