// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	carModelsFieldNames          = builder.RawFieldNames(&CarModels{})
	carModelsRows                = strings.Join(carModelsFieldNames, ",")
	carModelsRowsExpectAutoSet   = strings.Join(stringx.Remove(carModelsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	carModelsRowsWithPlaceHolder = strings.Join(stringx.Remove(carModelsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCarModelsIdPrefix = "cache:carModels:id:"
)

type (
	carModelsModel interface {
		Insert(ctx context.Context, data *CarModels) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CarModels, error)
		Update(ctx context.Context, data *CarModels) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCarModelsModel struct {
		sqlc.CachedConn
		table string
	}

	CarModels struct {
		Id       uint64  `db:"id"`
		SeriesId uint64  `db:"series_id"`
		Name     string  `db:"name"`
		Year     int64   `db:"year"`
		Price    float64 `db:"price"`
		CoverImg string  `db:"cover_img"`
		Status   int64   `db:"status"`
	}
)

func newCarModelsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCarModelsModel {
	return &defaultCarModelsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`car_models`",
	}
}

func (m *defaultCarModelsModel) Delete(ctx context.Context, id uint64) error {
	carModelsIdKey := fmt.Sprintf("%s%v", cacheCarModelsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, carModelsIdKey)
	return err
}

func (m *defaultCarModelsModel) FindOne(ctx context.Context, id uint64) (*CarModels, error) {
	carModelsIdKey := fmt.Sprintf("%s%v", cacheCarModelsIdPrefix, id)
	var resp CarModels
	err := m.QueryRowCtx(ctx, &resp, carModelsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", carModelsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCarModelsModel) Insert(ctx context.Context, data *CarModels) (sql.Result, error) {
	carModelsIdKey := fmt.Sprintf("%s%v", cacheCarModelsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, carModelsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SeriesId, data.Name, data.Year, data.Price, data.CoverImg, data.Status)
	}, carModelsIdKey)
	return ret, err
}

func (m *defaultCarModelsModel) Update(ctx context.Context, data *CarModels) error {
	carModelsIdKey := fmt.Sprintf("%s%v", cacheCarModelsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, carModelsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.SeriesId, data.Name, data.Year, data.Price, data.CoverImg, data.Status, data.Id)
	}, carModelsIdKey)
	return err
}

func (m *defaultCarModelsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCarModelsIdPrefix, primary)
}

func (m *defaultCarModelsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", carModelsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCarModelsModel) tableName() string {
	return m.table
}
