// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	carMediaFieldNames          = builder.RawFieldNames(&CarMedia{})
	carMediaRows                = strings.Join(carMediaFieldNames, ",")
	carMediaRowsExpectAutoSet   = strings.Join(stringx.Remove(carMediaFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	carMediaRowsWithPlaceHolder = strings.Join(stringx.Remove(carMediaFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCarMediaIdPrefix = "cache:carMedia:id:"
)

type (
	carMediaModel interface {
		Insert(ctx context.Context, data *CarMedia) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CarMedia, error)
		Update(ctx context.Context, data *CarMedia) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCarMediaModel struct {
		sqlc.CachedConn
		table string
	}

	CarMedia struct {
		Id        uint64 `db:"id"`
		ModelId   uint64 `db:"model_id"`
		MediaType int64  `db:"media_type"` // 1:图片 2:视频
		Position  string `db:"position"`
		Url       string `db:"url"`
		Sort      int64  `db:"sort"`
	}
)

func newCarMediaModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCarMediaModel {
	return &defaultCarMediaModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`car_media`",
	}
}

func (m *defaultCarMediaModel) Delete(ctx context.Context, id uint64) error {
	carMediaIdKey := fmt.Sprintf("%s%v", cacheCarMediaIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, carMediaIdKey)
	return err
}

func (m *defaultCarMediaModel) FindOne(ctx context.Context, id uint64) (*CarMedia, error) {
	carMediaIdKey := fmt.Sprintf("%s%v", cacheCarMediaIdPrefix, id)
	var resp CarMedia
	err := m.QueryRowCtx(ctx, &resp, carMediaIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", carMediaRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCarMediaModel) Insert(ctx context.Context, data *CarMedia) (sql.Result, error) {
	carMediaIdKey := fmt.Sprintf("%s%v", cacheCarMediaIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, carMediaRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ModelId, data.MediaType, data.Position, data.Url, data.Sort)
	}, carMediaIdKey)
	return ret, err
}

func (m *defaultCarMediaModel) Update(ctx context.Context, data *CarMedia) error {
	carMediaIdKey := fmt.Sprintf("%s%v", cacheCarMediaIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, carMediaRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ModelId, data.MediaType, data.Position, data.Url, data.Sort, data.Id)
	}, carMediaIdKey)
	return err
}

func (m *defaultCarMediaModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCarMediaIdPrefix, primary)
}

func (m *defaultCarMediaModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", carMediaRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCarMediaModel) tableName() string {
	return m.table
}
