// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	carSeriesFieldNames          = builder.RawFieldNames(&CarSeries{})
	carSeriesRows                = strings.Join(carSeriesFieldNames, ",")
	carSeriesRowsExpectAutoSet   = strings.Join(stringx.Remove(carSeriesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	carSeriesRowsWithPlaceHolder = strings.Join(stringx.Remove(carSeriesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCarSeriesIdPrefix = "cache:carSeries:id:"
)

type (
	carSeriesModel interface {
		Insert(ctx context.Context, data *CarSeries) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CarSeries, error)
		Update(ctx context.Context, data *CarSeries) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCarSeriesModel struct {
		sqlc.CachedConn
		table string
	}

	CarSeries struct {
		Id      uint64 `db:"id"`
		BrandId uint64 `db:"brand_id"`
		Name    string `db:"name"`
	}
)

func newCarSeriesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCarSeriesModel {
	return &defaultCarSeriesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`car_series`",
	}
}

func (m *defaultCarSeriesModel) Delete(ctx context.Context, id uint64) error {
	carSeriesIdKey := fmt.Sprintf("%s%v", cacheCarSeriesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, carSeriesIdKey)
	return err
}

func (m *defaultCarSeriesModel) FindOne(ctx context.Context, id uint64) (*CarSeries, error) {
	carSeriesIdKey := fmt.Sprintf("%s%v", cacheCarSeriesIdPrefix, id)
	var resp CarSeries
	err := m.QueryRowCtx(ctx, &resp, carSeriesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", carSeriesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCarSeriesModel) Insert(ctx context.Context, data *CarSeries) (sql.Result, error) {
	carSeriesIdKey := fmt.Sprintf("%s%v", cacheCarSeriesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, carSeriesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.BrandId, data.Name)
	}, carSeriesIdKey)
	return ret, err
}

func (m *defaultCarSeriesModel) Update(ctx context.Context, data *CarSeries) error {
	carSeriesIdKey := fmt.Sprintf("%s%v", cacheCarSeriesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, carSeriesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.BrandId, data.Name, data.Id)
	}, carSeriesIdKey)
	return err
}

func (m *defaultCarSeriesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCarSeriesIdPrefix, primary)
}

func (m *defaultCarSeriesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", carSeriesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCarSeriesModel) tableName() string {
	return m.table
}
