// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	carSpecsFieldNames          = builder.RawFieldNames(&CarSpecs{})
	carSpecsRows                = strings.Join(carSpecsFieldNames, ",")
	carSpecsRowsExpectAutoSet   = strings.Join(stringx.Remove(carSpecsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	carSpecsRowsWithPlaceHolder = strings.Join(stringx.Remove(carSpecsFieldNames, "`model_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCarSpecsModelIdPrefix = "cache:carSpecs:modelId:"
)

type (
	carSpecsModel interface {
		Insert(ctx context.Context, data *CarSpecs) (sql.Result, error)
		FindOne(ctx context.Context, modelId uint64) (*CarSpecs, error)
		Update(ctx context.Context, data *CarSpecs) error
		Delete(ctx context.Context, modelId uint64) error
	}

	defaultCarSpecsModel struct {
		sqlc.CachedConn
		table string
	}

	CarSpecs struct {
		ModelId      uint64         `db:"model_id"`      // 关联车型ID，作为主键
		Engine       string         `db:"engine"`        // 发动机，如：1.5T 192马力 L4
		Transmission string         `db:"transmission"`  // 变速箱，如：CVT无级变速
		Dimensions   string         `db:"dimensions"`    // 长宽高(mm)
		BaseParams   sql.NullString `db:"base_params"`   // 基础参数(JSON结构)
		SafetyParams sql.NullString `db:"safety_params"` // 安全配置(JSON结构)
		MediaParams  sql.NullString `db:"media_params"`  // 多媒体配置(JSON结构)
	}
)

func newCarSpecsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCarSpecsModel {
	return &defaultCarSpecsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`car_specs`",
	}
}

func (m *defaultCarSpecsModel) Delete(ctx context.Context, modelId uint64) error {
	carSpecsModelIdKey := fmt.Sprintf("%s%v", cacheCarSpecsModelIdPrefix, modelId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `model_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, modelId)
	}, carSpecsModelIdKey)
	return err
}

func (m *defaultCarSpecsModel) FindOne(ctx context.Context, modelId uint64) (*CarSpecs, error) {
	carSpecsModelIdKey := fmt.Sprintf("%s%v", cacheCarSpecsModelIdPrefix, modelId)
	var resp CarSpecs
	err := m.QueryRowCtx(ctx, &resp, carSpecsModelIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `model_id` = ? limit 1", carSpecsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, modelId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCarSpecsModel) Insert(ctx context.Context, data *CarSpecs) (sql.Result, error) {
	carSpecsModelIdKey := fmt.Sprintf("%s%v", cacheCarSpecsModelIdPrefix, data.ModelId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, carSpecsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ModelId, data.Engine, data.Transmission, data.Dimensions, data.BaseParams, data.SafetyParams, data.MediaParams)
	}, carSpecsModelIdKey)
	return ret, err
}

func (m *defaultCarSpecsModel) Update(ctx context.Context, data *CarSpecs) error {
	carSpecsModelIdKey := fmt.Sprintf("%s%v", cacheCarSpecsModelIdPrefix, data.ModelId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `model_id` = ?", m.table, carSpecsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Engine, data.Transmission, data.Dimensions, data.BaseParams, data.SafetyParams, data.MediaParams, data.ModelId)
	}, carSpecsModelIdKey)
	return err
}

func (m *defaultCarSpecsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCarSpecsModelIdPrefix, primary)
}

func (m *defaultCarSpecsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `model_id` = ? limit 1", carSpecsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCarSpecsModel) tableName() string {
	return m.table
}
