// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	favoritesFieldNames          = builder.RawFieldNames(&Favorites{})
	favoritesRows                = strings.Join(favoritesFieldNames, ",")
	favoritesRowsExpectAutoSet   = strings.Join(stringx.Remove(favoritesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	favoritesRowsWithPlaceHolder = strings.Join(stringx.Remove(favoritesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFavoritesIdPrefix            = "cache:favorites:id:"
	cacheFavoritesUserIdModelIdPrefix = "cache:favorites:userId:modelId:"
)

type (
	favoritesModel interface {
		Insert(ctx context.Context, data *Favorites) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Favorites, error)
		FindOneByUserIdModelId(ctx context.Context, userId uint64, modelId uint64) (*Favorites, error)
		Update(ctx context.Context, data *Favorites) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultFavoritesModel struct {
		sqlc.CachedConn
		table string
	}

	Favorites struct {
		Id         uint64    `db:"id"`
		UserId     uint64    `db:"user_id"`
		ModelId    uint64    `db:"model_id"`
		CreateTime time.Time `db:"create_time"`
	}
)

func newFavoritesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFavoritesModel {
	return &defaultFavoritesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`favorites`",
	}
}

func (m *defaultFavoritesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	favoritesIdKey := fmt.Sprintf("%s%v", cacheFavoritesIdPrefix, id)
	favoritesUserIdModelIdKey := fmt.Sprintf("%s%v:%v", cacheFavoritesUserIdModelIdPrefix, data.UserId, data.ModelId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, favoritesIdKey, favoritesUserIdModelIdKey)
	return err
}

func (m *defaultFavoritesModel) FindOne(ctx context.Context, id uint64) (*Favorites, error) {
	favoritesIdKey := fmt.Sprintf("%s%v", cacheFavoritesIdPrefix, id)
	var resp Favorites
	err := m.QueryRowCtx(ctx, &resp, favoritesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", favoritesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFavoritesModel) FindOneByUserIdModelId(ctx context.Context, userId uint64, modelId uint64) (*Favorites, error) {
	favoritesUserIdModelIdKey := fmt.Sprintf("%s%v:%v", cacheFavoritesUserIdModelIdPrefix, userId, modelId)
	var resp Favorites
	err := m.QueryRowIndexCtx(ctx, &resp, favoritesUserIdModelIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `model_id` = ? limit 1", favoritesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, modelId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFavoritesModel) Insert(ctx context.Context, data *Favorites) (sql.Result, error) {
	favoritesIdKey := fmt.Sprintf("%s%v", cacheFavoritesIdPrefix, data.Id)
	favoritesUserIdModelIdKey := fmt.Sprintf("%s%v:%v", cacheFavoritesUserIdModelIdPrefix, data.UserId, data.ModelId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, favoritesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.ModelId)
	}, favoritesIdKey, favoritesUserIdModelIdKey)
	return ret, err
}

func (m *defaultFavoritesModel) Update(ctx context.Context, newData *Favorites) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	favoritesIdKey := fmt.Sprintf("%s%v", cacheFavoritesIdPrefix, data.Id)
	favoritesUserIdModelIdKey := fmt.Sprintf("%s%v:%v", cacheFavoritesUserIdModelIdPrefix, data.UserId, data.ModelId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, favoritesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.ModelId, newData.Id)
	}, favoritesIdKey, favoritesUserIdModelIdKey)
	return err
}

func (m *defaultFavoritesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFavoritesIdPrefix, primary)
}

func (m *defaultFavoritesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", favoritesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFavoritesModel) tableName() string {
	return m.table
}
