// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	reviewsFieldNames          = builder.RawFieldNames(&Reviews{})
	reviewsRows                = strings.Join(reviewsFieldNames, ",")
	reviewsRowsExpectAutoSet   = strings.Join(stringx.Remove(reviewsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	reviewsRowsWithPlaceHolder = strings.Join(stringx.Remove(reviewsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheReviewsIdPrefix = "cache:reviews:id:"
)

type (
	reviewsModel interface {
		Insert(ctx context.Context, data *Reviews) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Reviews, error)
		Update(ctx context.Context, data *Reviews) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultReviewsModel struct {
		sqlc.CachedConn
		table string
	}

	Reviews struct {
		Id         uint64    `db:"id"`
		UserId     uint64    `db:"user_id"`
		ModelId    uint64    `db:"model_id"`
		Score      float64   `db:"score"`
		Content    string    `db:"content"`
		Likes      int64     `db:"likes"`
		CreateTime time.Time `db:"create_time"`
	}
)

func newReviewsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultReviewsModel {
	return &defaultReviewsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`reviews`",
	}
}

func (m *defaultReviewsModel) Delete(ctx context.Context, id uint64) error {
	reviewsIdKey := fmt.Sprintf("%s%v", cacheReviewsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, reviewsIdKey)
	return err
}

func (m *defaultReviewsModel) FindOne(ctx context.Context, id uint64) (*Reviews, error) {
	reviewsIdKey := fmt.Sprintf("%s%v", cacheReviewsIdPrefix, id)
	var resp Reviews
	err := m.QueryRowCtx(ctx, &resp, reviewsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", reviewsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReviewsModel) Insert(ctx context.Context, data *Reviews) (sql.Result, error) {
	reviewsIdKey := fmt.Sprintf("%s%v", cacheReviewsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, reviewsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.ModelId, data.Score, data.Content, data.Likes)
	}, reviewsIdKey)
	return ret, err
}

func (m *defaultReviewsModel) Update(ctx context.Context, data *Reviews) error {
	reviewsIdKey := fmt.Sprintf("%s%v", cacheReviewsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, reviewsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.ModelId, data.Score, data.Content, data.Likes, data.Id)
	}, reviewsIdKey)
	return err
}

func (m *defaultReviewsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheReviewsIdPrefix, primary)
}

func (m *defaultReviewsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", reviewsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultReviewsModel) tableName() string {
	return m.table
}
